server:
  port: 15000
spring:
  application:
    name: login-service
  datasource:
    url: jdbc:mysql:///insurance
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8763/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳续约时间
    lease-expiration-duration-in-seconds: 15 #剔除服务时间