server:
  port: 10100
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/insurance
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 111111
    type: com.alibaba.druid.pool.DruidDataSource
  activiti:
    database-schema: update
    check-process-definitions: false
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
mybatis:
  mapper-locations: mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳续约时间
    lease-expiration-duration-in-seconds: 15 #剔除服务时间